name: PyNet CI
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                
      - name: Get CUDA 
        run: .github\workflows\install-cuda-windows.ps1
          
      - name: Running cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ../PyNet.Infrastructure 
      
      - name: Make Modules Public
        run: | 
          cd .github
          .\Add-BmiSetting "${{ github.workspace }}/build/PyNet.Infrastructure.vcxproj"
          .\Add-BmiSetting "${{ github.workspace }}/build/libs/PyNet.Models.Cuda/PyNet.Models.Cuda.vcxproj"
        
                
      - name: Build Solution
        run: |
          cd build
          cmake --build ./  --config release
          dir
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PyNet.Infrastructure
          path: "${{ github.workspace }}/build/Release"
