name: PyNet CI
on: [push]
jobs:
  Build-And-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get CUDA 
        run: |
          curl -o https://developer.download.nvidia.com/compute/cuda/11.6.1/network_installers/cuda_11.6.1_windows_network.exe > ../cuda_11.6.1_windows_network.exe
          cd ../
          .\cuda_11.6.1_windows_network.exe
          
      - name: Running cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ../PyNet.Infrastructure
                
      - name: Build Solution
        run: |
          cd build
          MSBuild.exe PyNet.Infrastructure.sln
