name: PyNet CI
on: [push]
jobs:
  Build-And-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
        
      - name: Get CUDA 
      
        run: |
          conda install cuda -c nvidia
          setx CUDA_PATH "C:\Miniconda\envs\test"
          
      - name: Running cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -DCUDAToolkit_ROOT="C:\Miniconda\envs\test" ../PyNet.Infrastructure 
                
      - name: Build Solution
        run: |
          cd build
          MSBuild.exe PyNet.Infrastructure.sln
