name: PyNet CI
on: [push]
jobs:
  Build-And-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Installing vcpkg
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          
      - name: Running cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}
                /../vcpkg/scripts/buildsystems/vcpkg.cmake
                
      - name: Build Solution
        run: |
          cd build
          MSBuild.exe PyNet.Infrastructure.sln
