name: PyNet CI
on: [push]
jobs:
  Build-And-Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - run: msbuild PyNet.Infrastructure.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
