name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
